# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heysprech-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heysprech-back
  template:
    metadata:
      labels:
        app: heysprech-back
    spec:
      containers:
        - name: heysprech-back
          image: registry.tiakalo.org/backend-heysprech:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              value: 'postgresql://postgres:password@postgres:5432/defheysprechault_db?search_path=public'
      imagePullSecrets:
        - name: nexus-registry-secret
---
# svc
apiVersion: v1
kind: Service
metadata:
  name: heysprech-back
spec:
  selector:
    app: heysprech-back
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-api-heysprech.tiakalo.org
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - dev-api-heysprech.tiakalo.org
      secretName: dev-api-heysprech.tiakalo.org-tls
  rules:
    - host: dev-api-heysprech.tiakalo.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heysprech-back
                port:
                  number: 3000