name: Deployment

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js (for tooling, not bun)
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Clean server folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            rm -rf /var/www/node-heysprech-api/!(.env|.env.production)

      - name: Upload files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          source: "./"
          target: "/var/www/node-heysprech-api/"
          overwrite: true

      - name: Install and start app with Bun and PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: 22
          script: |
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH"

            if ! command -v bun &> /dev/null
            then
              curl -fsSL https://bun.sh/install | bash
              export PATH="$HOME/.bun/bin:$PATH"
            fi

            cd /var/www/node-heysprech-api/

            rm -rf node_modules package-lock.json

            bun install
            bun run build
            pm2 delete heysprech-api || true
            PORT=5000 pm2 start bun --name heysprech-api -- run prod
            pm2 save
